### ISSUE TITLE
Include comment to slack notification

### ISSUE THREAD

**Issue by emmanuelbuah** [kanboard/plugin-slack#1]
It would be great to send the actual comment message with the slack notification to reduce going to KB for every comment made at a task.

**Comment by ghost** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
