### ISSUE TITLE
Preview Thumbnail

### ISSUE THREAD

**Issue by barulho77** [kanboard/plugin-slack#11]
People,
Congrats. This plugin is really very useful. It is possible to include a thumbnail preview of the attached file (images), as with integration with Trello?

It would help a lot.

In my teams the final layout of all design creations are attached in the task. With the notifications it becomes much easier to check.

Regards!

![image](https://user-images.githubusercontent.com/1137187/28248679-b3e7d400-6a1e-11e7-8a0e-ab49b8e73f91.png)

**Comment by ghost** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
