### ISSUE TITLE
Discord Integration

### ISSUE THREAD

**Issue by tbienias** [kanboard/plugin-slack#12]
I just wanted to point out that this plugin also works with Discord!
The setup is the same, but you have to append "slack" to your Discord webhook and voila you get messages to Discord using this plugin - awesome! 
Would be nice to mention this in the documentation.

**Comment by ErroneousFatality** [comment]
@JACKSONMEISTER I don't understand what you mean by append "slack" to your Discord webhook. I can't change the Discord webhook url in the app.

**Comment by tbienias** [comment]
@ErroneousFatality Just take your Discord webhook url and append "slack" (without the quotes) to it - thats all!

**Comment by ErroneousFatality** [comment]
@JACKSONMEISTER 
So my webhook is (mock) https://discordapp.com/api/webhooks/1234567890/abcdefghijkl
Into Kanboard project integrations for slack I inserted it as (mock) https://discordapp.com/api/webhooks/1234567890/abcdefghijklslack
Still nothing happens (Notifications are on for slack integration)

**Comment by tbienias** [comment]
Please try:
https://discordapp.com/api/webhooks/1234567890/abcdefghijkl/slack
(i missed the slash)

**Comment by ErroneousFatality** [comment]
@JACKSONMEISTER That made it work. Thank you very much!

**Comment by ghost** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
