### ISSUE TITLE
More specific setup instructions would be great

### ISSUE THREAD

**Issue by mcbejn** [kanboard/plugin-slack#13]
Hi guys,

This is a great plugin and we've been using it for a while, but we can't seem to figure out the way to do personal notifications. 

It's not clear how to setup user specific notifications - do we need to create webhooks in slack for each separate user?

We've got all our notifications coming into one slack channel at the moment, but it would be much better to follow only tasks related to the people involved with it.

Thanks in advance!

**Comment by ghost** [comment]
This issue has been closed automatically by a bot for inactivity. For more information, read the [FAQ](https://docs.kanboard.org/en/1.2.6/developer_guide/faq.html).
