### ISSUE TITLE
Internal error of Slack plugin

### ISSUE THREAD

**Issue by AlgyTaylor** [kanboard/plugin-slack#3]
### Expected behaviour

I have added the slack plugin folder to my plugins directory.  I have a custom plugin folder, not the default. Slack plugin should load.
### Actual behaviour

I receive an error
"Internal Error: Unable to load this plugin class \Kanboard\Plugin\Slack\Plugin"
### Steps to reproduce
1. Copy slack plugin in to Kanboard
2. Go to kanboard
3. Have error
### Configuration

```
Application version: 1.0.27
PHP version: 7.0.2
PHP SAPI: apache2handler
OS version: Windows NT 6.0
Database driver: postgres
Database version: 9.4.0
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
```

Plugin version 1.0.2
Plugin folder changed location.

**Comment by fguillot** [comment]
Custom plugin folder is now handled with a most recent version of Kanboard.
