### ISSUE TITLE
Click to Slack message appendix " ... - view the task on Kanboard" leads to error

### ISSUE THREAD

**Issue by StanSiska** [kanboard/plugin-slack#4]
We downloaded today (31.05.2016) latest Kanboard instance and Slack plugin (1.0.4) directly from GitHub repository.

When we go to Slack and click to generated link "... view the task on Kanboard", it gives following error linked to recent Controllers rename:

**Internal Error: Controller not found** 
(generated link --> http://centos7/kanboard/?controller=**task**&action=show&task_id=855&project_id=28)
(correct link --> http://centos7/kanboard/?controller=**TaskViewController**&action=show&task_id=855&project_id=28)

Additional info:

```
Application version: master
PHP version: 5.4.16
PHP SAPI: apache2handler
OS version: Linux 3.10.0-327.13.1.el7.x86_64
Database driver: sqlite
Database version: 3.7.17
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0
```

**Comment by fguillot** [comment]
Fixed a long time ago.
