### ISSUE TITLE
How to debug slack

### ISSUE THREAD

**Issue by asangansi** [kanboard/plugin-slack#5]
Thanks so much for this integration.
We just upgraded kanboard from 1.0.27 to 1.0.31  and installed Slack through the interface

We haven't been able to get slack working again, even after regenerating webhook url.
And we are now wondering how to enable debug mode.

Thanks so much

**Comment by ghost** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
