### ISSUE TITLE
Error sending overdue notifications to Slack

### ISSUE THREAD

**Issue by rolf-thomas** [kanboard/plugin-slack#6]
### Expected behaviour
Send overdue notifications to Slack

### Actual behaviour
```
PHP Notice:  Undefined index: task in /var/www/[folder]/public_html/plugins/Slack/Notification/Slack.php on line 30
PHP Catchable fatal error:  Argument 3 passed to Kanboard\Plugin\Slack\Notification\Slack::sendMessage() must be of the type array, null given, called in /var/www/[folder]/public_html/plugins/Slack/Notification/Slack.php on line 31 and defined in /var/www/[folder]/public_html/plugins/Slack/Notification/Slack.php on line 98
```

### Steps to reproduce
- copy plugin source to `plugins/Slack`
- configure slack incomming webhook-url under `user > profile > integration` (or `admin > settings > integrations`)
- activate Slack via `user > profile > notifications`
- run `./cli notification:overdue-tasks --group` on shell

### Configuration
Version: 1.0.35
PHP Version: 5.5.9-1ubuntu4.20
PHP SAPI: apache2handler
OS Version: Linux 3.13.0-57-generic
Datenbanktreiber: mysql
Datenbank Version: 5.5.53-0ubuntu0.14.04.1
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14

**Comment by fguillot** [comment]
Thank you, this is now fixed. You can download the last version of the plugin.
