### ISSUE TITLE
[Feature Request] Include URL in Slack Notification

### ISSUE THREAD

**Issue by levlaz** [kanboard/plugin-slack#7]
It would be awesome to be able to have the URL to the task in the slack notification.

**Comment by fguillot** [comment]
If you set the application url in the application settings, you should have a link to the task in the notifications: https://github.com/kanboard/plugin-slack/blob/master/Notification/Slack.php#L84-L87

**Comment by levlaz** [comment]
Thanks so much @fguillot works like a charm! Sorry for the noise :)
