### ISSUE TITLE
Feature request:  Tag-dependent channel notifications

### ISSUE THREAD

**Issue by george-viaud** [kanboard/plugin-slack#8]
Feature would send messages to specific #channel(s) based on tags.

Rules would be defined similar to:

If tag X, then send to #channel on (change|delete|close|etc)

In some cases, multiple rules would be nice such that several channels could receive the same notifications.

This is a rough idea atm - we use Tags in a way that lets us unify projects under one project but still distinguish between them - in this way pertinent changes get to the appropriate team's #channel(s)

**Comment by ghost** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
