### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by baestu** [kanboard/plugin-slack#9]
Hi 

Would be great if the messages send to the slackbot would inlcude a direct link to the task:
Currently it comes as pure text amd it would be very helpful if its possible to click a link in the message to jump directly to the task.
here a example: 
Current:
admin changed the assignee of the task #20 to username (teasd)

with link:
admin changed the assignee of the **task #20**(<-link) to Sebastian Mutti (teasd)

**Comment by fguillot** [comment]
This is already available, see #7

**Comment by baestu** [comment]
Hi
Thanks for the fast answer, works now didn't realize that the application url needs to be set,. 
I will close the issue.
